version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories: 
    - "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
